repos:
  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black
        types: [python]
        language_version: python3.8
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
