# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ConvertDEMtoGeoTiff
                                 A QGIS plugin
 DEMをGeoTiffに変換します
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-24
        copyright            : (C) 2019 by MIERUNE.Inc
        email                : nishio@mierune.co.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ConvertDEMtoGeoTiff class from file ConvertDEMtoGeoTiff.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .convert_dem_to_geotiff import ConvertDEMtoGeoTiff
    return ConvertDEMtoGeoTiff(iface)
