[tool.black]
line-length = 79
target-version = ['py38']
include = '\.py$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | convert_fgd_dem
)/
'''
